### ISSUE TITLE
Font color when using burp's dark theme

### ISSUE THREAD

**Issue by slicingmelon** [0xC01DF00D/Collabfiltrator#5]
Hello,

I am really excited to use your extension, I've read the blog post as well. There is a small issue in regards of the payload/output font color when using the dark theme. You cannot see anything in there.

![image](https://user-images.githubusercontent.com/57750222/101469955-0c358b00-394e-11eb-874c-48da1618597e.png)

Also note that date's command output was not retrieved either.

**Comment by 0xC01DF00D** [comment]
Thanks for bringing this to my attention. I will investigate this issue.

**Comment by 0xC01DF00D** [comment]
Fixed in 2.1 update.
